/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applicationbillet;

import Data.Vols;
import java.awt.Frame;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import libs.TickmapClient;
import protocole.TICKMAPTYPE;
import protocole.tickmap;

/**
 *
 * @author 'Toine
 */
public class AchatBillet extends javax.swing.JDialog {

    public TickmapClient tc=null;
    public Frame parentFrame =null;
    public Vols v=null;
    
    /**
     * Creates new form AchatBillet
     */
    public AchatBillet(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        parentFrame = parent;
    }
    
    public AchatBillet(java.awt.Frame parent, boolean modal, Vols pv,TickmapClient ptc) {
        super(parent, modal);
        initComponents();
        tc =ptc;
        v =pv;
        infoVolsLabel.setText(v.toString());
        nbrSpinner.setModel(new SpinnerNumberModel(0, 0, v.getNbrDispo(),1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoVolsLabel = new javax.swing.JLabel();
        nbrSpinner = new javax.swing.JSpinner();
        questionLabel = new javax.swing.JLabel();
        achatButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        infoVolsLabel.setText("jLabel1");

        nbrSpinner.setModel(new javax.swing.SpinnerNumberModel());

        questionLabel.setText("Combien de billet voulez vous ?");

        achatButton.setText("Achat");
        achatButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                achatButtonMouseClicked(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(questionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nbrSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(infoVolsLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(achatButton)
                        .addGap(158, 158, 158)
                        .addComponent(cancelButton)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(infoVolsLabel)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nbrSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questionLabel))
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(achatButton)
                    .addComponent(cancelButton))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelButtonMouseClicked

    private void achatButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_achatButtonMouseClicked
        // TODO add your handling code here:
        if((int)nbrSpinner.getValue() > 0){
            tc.write(new tickmap(TICKMAPTYPE.ACHAT, ""+v.getIdVols()+"#"+(int)nbrSpinner.getValue()));
            tickmap response = tc.read();
            if(response.getType() == TICKMAPTYPE.NOK){
                JOptionPane.showMessageDialog(this,"ERREUR D'ACHAT", "title", JOptionPane.INFORMATION_MESSAGE);
            }else{
                ConfirmationAchat ca = new ConfirmationAchat(this.parentFrame,true,response.getMessage(), tc);
                ca.setVisible(true);
            }
        }else{
            JOptionPane.showMessageDialog(this,"Veuillez acheter plus que 0 billet", "title", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_achatButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AchatBillet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AchatBillet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AchatBillet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AchatBillet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AchatBillet dialog = new AchatBillet(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton achatButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel infoVolsLabel;
    private javax.swing.JSpinner nbrSpinner;
    private javax.swing.JLabel questionLabel;
    // End of variables declaration//GEN-END:variables
}
